apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      serviceAccountName: default
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
      volumes:
      - name: vol
        emptyDir: {}
      containers:
      - name: devsecops-container
        image: replace
        volumeMounts:
        - mountPath: /tmp
          name: vol
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
spec:
  selector:
    app: devsecops
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: LoadBalancer
